openapi: 3.0.0
info:
  title: Stats API
  description: This API generates and stores statistics for events
  contact:
    email: hli197@my.bcit.ca
  version: "1.0.0"

paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets statistics on events
      tags:
        - statistics
      responses:
        "200":
          description: Successfully returned event statistics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventStats"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /health:
    get:
      tags:
        - admins
      summary: Gets the event health
      operationId: app.get_health
      description: Gets status of service is running or offline
      responses:
        "200":
          description: backend service is running
        "400":
          description: backend service is down

tags:
  - name: statistics
    description: Operations related to event statistics

components:
  schemas:
    EventStats:
      type: object
      required:
        - num_bb_received
        - num_rb_received
        - avg_borrow_duration
        - avg_return_duration
        - max_return_late_fee
      properties:
        num_bb_received:
          type: integer
          example: 1000
          description: Number of borrow book events received
        num_rb_received:
          type: integer
          example: 750
          description: Number of return book events received
        avg_borrow_duration:
          type: number
          example: 5.5
          description: Average duration of borrow book events
        avg_return_duration:
          type: number
          example: 4.5
          description: Average duration of return book events
        max_return_late_fee:
          type: number
          format: float
          example: 10.0
          description: Maximum late fee among return book events
